### ISSUE TITLE
Got an interesting crash about Late Model Precacher

### ISSUE THREAD

**Issue by fbef0102** [Psykotikism/Late_Model_Precacher#1]
Hello, Psyk0tik

My friends usually play custom maps, so I tell them install [Late Model Precacher](https://forums.alliedmods.net/showthread.php?t=337273), but recently there is a crash relate to this plugin. 

Logs:
![image](https://github.com/user-attachments/assets/7049dff3-d5be-4ae1-808c-f86015c65a9f)

Crash ID: [sekxh5wmgkvc](https://crash.limetech.org/sekxh5wmgkvc), [jjhy6z4yprnt](https://crash.limetech.org/jjhy6z4yprnt)
![image](https://i.imgur.com/nkVsBRb.png)

View Raw Stack:
https://pastebin.com/qMqgYZtJ

I am not sure, it seems that the plugin tried to preache model number <b>"*xxx" which is invalid</b> I guess?

**Comment by Psykotikism** [comment]
Yeah the model name seems unusual. Maybe the model itself is invalid. I would suggest disabling the plugin on that campaign. All the plugin does is precache uncached models, but maybe model "*209" doesn't represent a valid model.

**Comment by fbef0102** [comment]
Okay, Turns out that custom map is broken, server still crash without plugin.
![image](https://github.com/user-attachments/assets/f5da33be-7dcd-4e5c-bdac-57fba8dfe9fb)

Ignore this issue
